  
name: Benchmark
on:
  pull_request:
    branches:
      - master

jobs:
  benchmark:
    name: Run Go benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
      - name: Set GOPATH
        # temporary fix
        # see https://github.com/actions/setup-go/issues/14
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - uses: actions/checkout@v1
        with:
          path: ./src/github.com/${{ github.repository }}
      #- name: Run benchmark
      #  run: cd test/bench && go test -bench=. -benchtime=30s | tee output.txt
      - name: Perform benchmarks
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        uses: shipt/go-benchmark-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
